<a href="https://colab.research.google.com/github/Khushi007-bit/python-assingnment-14/blob/main/session14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

question1


In [1]:
# Import NumPy library
import numpy as np

# Create a 2D array of shape (5,6) with random integers between 10 and 100
arr = np.random.randint(10, 101, (5, 6))

# Print the array
print("Array:")
print(arr)

# Print the shape of the array
print("Shape =", arr.shape)

# Print the total number of elements
print("Size =", arr.size)

# Print the data type
print("Data Type =", arr.dtype)


Array:
[[ 29  95  80  97  53  63]
 [ 17  71  51  37  32  69]
 [ 12  22  76  91  37  38]
 [ 31  84  28  64  62  71]
 [ 32  14 100  95  60  61]]
Shape = (5, 6)
Size = 30
Data Type = int64


question2

In [2]:
import numpy as np
#crete 1D array with 20 random number betn 1 and 50
arr=np.random.randint(1,50,20)     #using np.random.randint()
print("Array=",arr)
#sum of all element
print("Sum of element=",arr.sum())
#Mean and standard deviation
print("Mean=",arr.mean())
print("Standard Deviation=",arr.std())
#minimum value and its index(argmin)
print("Minimum value=",arr.argmin())
#maximun value and its index(argmax)
print("Maximum value=",arr.argmax())


Array= [19 43 43  7 16 25 33 17 38 38 37 47  2 49  5 41 48 17 43 27]
Sum of element= 595
Mean= 29.75
Standard Deviation= 14.85555451674558
Minimum value= 12
Maximum value= 13


question3

In [3]:
import numpy as np
#generate 4x5 matrix of random integer betn 20 and 80
print("2D array with matrix(4x5):")
arr=np.random.randint(20,80,(4,5))
print(arr)
#minimun and maximum value
print("Minimum value=",np.min(arr))
print("Maximun value=",np.max(arr))
#Sum of all Element
print("Sum of matrix=",np.sum(arr))
#Mean and standard deviation
print("Mean=",np.mean(arr))
print("Standard deviation=",np.std(arr))
#print the sum of each row and each column
print("Sum of each each row=",np.sum(arr,axis=1))
print("Sum of each column=",np.sum(arr,axis=0))



2D array with matrix(4x5):
[[20 27 36 39 60]
 [34 75 48 75 76]
 [28 75 62 39 53]
 [69 54 59 26 67]]
Minimum value= 20
Maximun value= 76
Sum of matrix= 1022
Mean= 51.1
Standard deviation= 18.321844885272878
Sum of each each row= [182 308 257 275]
Sum of each column= [151 231 205 179 256]


question4


In [4]:
import numpy as np
#create 1D array contain number fron 1 to 24
print("1D Array:")
arr=np.arange(1,25)   #using np.arange()
print(arr)
#resape it into (4,6)
v1=arr.reshape(4,6)
print("Reshape into (4x6):","\n",v1)
#reshape it into (3,8)
v2=arr.reshape(3,8)
print("Reshape into (3x8):","\n",v2)
#reshape it into(2,3,4)(3D array)
v3=arr.reshape(2,3,4)
print("Reshape into (2,3,4)","\n",v3)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Reshape into (4x6): 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Reshape into (3x8): 
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Reshape into (2,3,4) 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


question5

In [5]:
import numpy as np
#create the array
arr=np.array([[10,20,30,40],
              [50,60,70,80],
              [90,100,110,120]])
print("Original matrixs")
print(arr)

#extract first row
print("\nFirst row:")
print(arr[0])
#extract last column
print("\nLast column:")
print(arr[:,-1])
#extract center 2x2 submatrix
print("\nCenter 2x2 Submatrix:")
print(arr[1:3,1:3])
#Extract all even numbers using boolean indexing
print("\nEven number:")
print(arr[arr%2==0])



Original matrixs
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First row:
[10 20 30 40]

Last column:
[ 40  80 120]

Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]

Even number:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


question6

In [6]:
import numpy as np
#create 5x5 matrix of random integer betn 1 and 100
print("5x5 Matrixs:")
arr=np.random.randint(1,101,(5,5))
#original array
print("Original array=")
print(arr)
#print digonal element
print("\nDiagonal element:")
print(np.diag(arr))
#print elements greater than 50
print("\nElements greater than 50=")
print(arr[arr>50])
#replace all element less tha 30 with 0
arr[arr<39]=0
#print modified array
print("\nModified array:")
print(arr)



5x5 Matrixs:
Original array=
[[49 81 88 49 15]
 [60 79 26 76  5]
 [51 75 80 98 81]
 [49 21 28 82 86]
 [33 81 27 92 59]]

Diagonal element:
[49 79 80 82 59]

Elements greater than 50=
[81 88 60 79 76 51 75 80 98 81 82 86 81 92 59]

Modified array:
[[49 81 88 49  0]
 [60 79  0 76  0]
 [51 75 80 98 81]
 [49  0  0 82 86]
 [ 0 81  0 92 59]]


question7


In [7]:
import numpy as np
#create two arrays:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
#addition,subtraction,multiplication,divison
print("Addition=",a+b)
print("Subtraction=",a-b)
print("Multiplication=",a*b)
print("Division=",a/b)
#Element wise power(**)
print("Elemnt wise power=",a**b)
#modulo operation
print("Modulo operation=",a%b)


Addition= [11 22 33 44]
Subtraction= [ 9 18 27 36]
Multiplication= [ 10  40  90 160]
Division= [10. 10. 10. 10.]
Elemnt wise power= [     10     400   27000 2560000]
Modulo operation= [0 0 0 0]


question8

In [8]:
import numpy as np
#crete 3x3 two matrices:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
#element-wise multiplication(*)
#multiplies corresponding elements of both matrices
print("element-wise multiplication=",A*B)
#matrix multiplication(@ or np.dot())
#multiplies rows of A with columns of B
print("Matrixs multiplication=",A@B)


element-wise multiplication= [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrixs multiplication= [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


question9

In [9]:
# Import NumPy
import numpy as np

# Create a 6x6 matrix of random numbers
arr = np.random.randn(6, 6)
# Print the matrix
print("Matrix:")
print(arr)
# Print shape, size and data type
print("Shape =", arr.shape)
print("Size =", arr.size)
print("Data Type =", arr.dtype)

# Print maximum and minimum index
print("Maximum Index =", np.argmax(arr))
print("Minimum Index =", np.argmin(arr))

# Print top-left 3x3 submatrix
print("Top-left 3x3 Submatrix:")
print(arr[:3, :3])

# Replace negative numbers with positive numbers
arr = np.abs(arr)
# Print modified matrix
print("Modified Matrix:")
print(arr)
# Print mean
print("Mean =", np.mean(arr))







Matrix:
[[ 0.87531042 -0.05758134 -0.34229125 -1.03784994  1.1953847  -0.28137863]
 [ 0.72603524 -0.04872262  0.26372421  0.73744904  0.09958617 -0.61043494]
 [ 0.29268426  0.22541188 -0.00547156 -0.78294208  0.03386444 -0.74894098]
 [ 0.01539865  0.18616894 -0.80166221 -0.80693585  0.93168149  0.2263279 ]
 [-0.7505269  -1.65009079  1.23303384 -1.30641886  0.33735734  0.72234149]
 [ 0.70822104 -1.15383951 -1.03772226 -1.19424194 -2.26097346 -0.56836295]]
Shape = (6, 6)
Size = 36
Data Type = float64
Maximum Index = 26
Minimum Index = 34
Top-left 3x3 Submatrix:
[[ 0.87531042 -0.05758134 -0.34229125]
 [ 0.72603524 -0.04872262  0.26372421]
 [ 0.29268426  0.22541188 -0.00547156]]
Modified Matrix:
[[0.87531042 0.05758134 0.34229125 1.03784994 1.1953847  0.28137863]
 [0.72603524 0.04872262 0.26372421 0.73744904 0.09958617 0.61043494]
 [0.29268426 0.22541188 0.00547156 0.78294208 0.03386444 0.74894098]
 [0.01539865 0.18616894 0.80166221 0.80693585 0.93168149 0.2263279 ]
 [0.7505269  1.65009079

question10

In [10]:
#Import NumPy library
import numpy as np

# Generate random marks for 10 students and 5 subjects
marks = np.random.randint(30, 101, (10, 5))

# Print the marks array
print("Student Marks:")
print(marks)

# Calculate total marks of each student
total = np.sum(marks, axis=1)
print("\nTotal Marks:")
print(total)

# Calculate average marks of each student
average = np.mean(marks, axis=1)
print("\nAverage Marks:")
print(average)

# Find student with highest total marks
print("\nHighest Total Marks Student Index =", np.argmax(total))

# Find student with lowest total marks
print("Lowest Total Marks Student Index =", np.argmin(total))

# Calculate overall class mean
print("\nClass Mean =", np.mean(marks))

# Calculate overall class standard deviation
print("Class Standard Deviation =", np.std(marks))

# Sort students based on total marks (highest first)
top3 = np.argsort(total)[-3:]

# Extract marks of top 3 students
print("\nMarks of Top 3 Students:")
print(marks[top3])

# Reshape the array (optional demonstration)
reshaped = marks.reshape(5, 10)
print("\nReshaped Array (5 x 10):")
print(reshaped)



Student Marks:
[[88 65 34 85 89]
 [90 42 73 89 65]
 [93 61 31 96 32]
 [64 51 87 40 41]
 [68 96 33 87 89]
 [68 81 37 67 36]
 [54 98 91 79 34]
 [31 42 97 40 99]
 [43 70 55 51 50]
 [90 50 79 54 77]]

Total Marks:
[361 359 313 283 373 289 356 309 269 350]

Average Marks:
[72.2 71.8 62.6 56.6 74.6 57.8 71.2 61.8 53.8 70. ]

Highest Total Marks Student Index = 4
Lowest Total Marks Student Index = 8

Class Mean = 65.24
Class Standard Deviation = 22.34597055399474

Marks of Top 3 Students:
[[90 42 73 89 65]
 [88 65 34 85 89]
 [68 96 33 87 89]]

Reshaped Array (5 x 10):
[[88 65 34 85 89 90 42 73 89 65]
 [93 61 31 96 32 64 51 87 40 41]
 [68 96 33 87 89 68 81 37 67 36]
 [54 98 91 79 34 31 42 97 40 99]
 [43 70 55 51 50 90 50 79 54 77]]
